---
# Post tasks

- name: "Find removed but configured apt packages"
  shell: "dpkg --list|grep ^rc|tr -s ' '|cut -d ' ' -f 2"
  register: apt_rc_packages
  changed_when: no
  when: ansible_os_family == "Debian"

- name: "Perform apt package cleanup"
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  changed_when: no
  ignore_errors: yes
  when: ansible_os_family == "Debian"
  with_items: "{{ apt_rc_packages.stdout_lines }}"
